# Don't edit this.
version: 4

# The highest number to check when testing a player's permissions for the maximum number of homes they can set.
max-home-permission-check: 3

# Settings regarding the AFK system.
afk-settings:
  # The time in seconds after which a player is automatically signalled as AFK.
  afk-time: 180

  # The time in seconds after which a player is automatically kicked for being AFK.
  afk-kick-time: 180

messages:
  # The message of the day which is displayed when a player joins the server.
  motd:
    - "Use <red>/help</red> for a list of commands and <red>/rules</red> for the rules."
    - "Currently online: <player_list>"

  # The rules which are displayed in the rules command.
  rules:
    - "<red>#1</red> Don't grief."
    - "<red>#2</red> Don't steal, lure or scam."
    - "<red>#3</red> Don't use hacks or abuse glitches."
    - "<red>#4</red> Don't advertise."
    - "<red>#5</red> Be respectful of others."
    - "<red>#6</red> Don't use profanity anywhere."
    - "<red>#7</red> Have fun!"
    - "<yellow>Type <click:run_command:/apply>/apply</click> to request removal from the greylist."

  # Messages that are broadcasted to the server on a regular basis.
  announcements:
    # How frequently should announcements occur (in ticks)?
    frequency: 24000

    messages:
      - "Need staff assistance? Use <red>/modreq</red> for help."
      - "Join us on discord: <red><click:open_url:'https://discord.gg/mMu7xaX'>https://discord.gg/mMu7xaX/</click></red>"
      - "Check out our website: <red><click:open_url:'https://froobworld.com/'>https://froobworld.com/</click></red>"

# Display name format for each group.
display-name-formats:
  default: <gray><name></gray>
  loyalist: <green><name></green>
  veteran: <dark_green><name></dark_green>
  trusted: <blue><name></blue>
  staff: <aqua><name></aqua>
  admin: <dark_red><name></dark_red>

# Chat channel prefix
chat-channel-prefix: "<dark_gray><c:<channel>></dark_gray> "

# Chat channel formatting
chat-channel-format: "<dark_gray><c:<channel>></dark_gray> <display_name><white>: <message></white>"

# Auto promote users based on their play time.
auto-promote:
  # Which track to promote the user along
  track: main

  # How long (in days) does the user need to have been playing for to be promoted from this group?
  required-time:
    other: -1
    default: 7
    loyalist: 30

# Random teleport settings.
random-teleport:
  # At most how many random teleports should a player be allowed to accrue?
  max-random-teleports: 3

  # How often (in minutes) should a player accrue a random teleport?
  regeneration-frequency: 240

  # In which worlds should random teleporting be enabled?
  enabled-worlds:
    - "froobworld"

  world-settings:
    default:
      # What is x coordinate of the centre around which to base random teleports?
      centre-x: 0

      # What is z coordinate of the centre around which to base random teleports?
      centre-z: 0

      # At most how far away on the x-axis should the random teleport be from the centre?
      radius-x: 7000

      # At most how far away on the z-axis should the random teleport be from the centre?
      radius-z: 7000

      exclusion-centre-x: 0

      exclusion-centre-z: 0

      # At least how far away on the x-axis should the random teleport be from the centre?
      exclusion-radius-x: 1500

      # At least how far away on the z-axis should the random teleport be from the centre?
      exclusion-radius-z: 1500
