# Don't edit this.
version: 3

# Settings related to bans.
ban-settings:
  # The URL provided to banned players for the purpose of appealing.
  ban-appeal-url: "froobworld.com/appeal"

  # The time in days after which a permanent ban will expire.
  auto-expiry-time: 730

  # The date after which permanent bans will no longer automatically expire.
  auto-expiry-cutoff: 2021-12-01

# Which commands should players who are in jail be allowed to use?
jail-command-whitelist:
  - /rules
  - /message
  - /mail

# Filter words in chat and on signs. Format "<word>:<replacement word>"
word-filters:
  - "hell:heck"

# Players who use these words will be shadow muted and a ticket will be opened.
highly-offensive-words: []