# Don't edit this.
version: 1

# The URL provided to banned players for the purpose of appealing.
ban-appeal-url: "froobworld.com"

# Which commands should players who are in jail be allowed to use?
jail-command-whitelist:
  - /rules
  - /message
  - /mail

# Filter words in chat and on signs. Format "<word>:<replacement word>"
word-filters:
  - "hell:heck"