# Don't edit this.
version: 3

# Settings related to bans.
ban-settings:
  # The URL provided to banned players for the purpose of appealing.
  ban-appeal-url: "froobworld.com/appeal"

  # The time in days after which a permanent ban will expire.
  auto-expiry-time: 730

  # The date after which permanent bans will no longer automatically expire.
  auto-expiry-cutoff: 2021-12-01

# Which commands should players who are in jail be allowed to use?
jail-command-whitelist:
  - /rules
  - /message
  - /mail

# Filter words in chat and on signs. Format "<word>:<replacement word>"
word-filters:
  - "hell:heck"

# Players who use these words will be shadow muted and a ticket will be opened.
highly-offensive-words: []

# Available deputy levels
deputy-levels:
  - "staff"
  - "admin"

deputy-settings:
  default:
    # Group that the deputy is added to during deputation
    deputy-group: ""

    # List of groups that a deputy can be selected from
    candidate-groups: []

    # Duration of deputation if not specified in command
    default-duration: 7d

    # Maximum allowed duration of deputation
    maximum-duration: 30d

    # How long before expiry should notification ticket be created and mail sent?
    expiry-notification-time: 12h

  staff:
    deputy-group: staff-deputy

    candidate-groups:
      - trusted

  admin:
    deputy-group: admin-deputy

    candidate-groups:
      - staff