# Don't edit this.
version: 1

# Settings for the view distance manager.
view-distance:
  # The capped (default) view distance.
  capped-view-distance: 16

  # The uncapped view distance.
  uncapped-view-distance: 32

world-border:
  default:
    use-border: true

    centre-x: 0

    centre-z: 0

    radius-x: 7000

    radius-z: 7000

    border-region-radius-x: 7000

    border-region-radius-z: 7000